Hezten\CoreBundle\Entity\City:
    type: mappedSuperclass
    table: hezten_city
    id: 
        id:
            type: integer
            unique: true
    fields:
        name:
            type: string
            length: 20