Hezten\CoreBundle\Entity\Course:
    type: mappedSuperclass
    table: hezten_course
    id: 
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        groupName:
            type: string
            length: 2
    
