Hezten\CoreBundle\Entity\Parents:
    type: mappedSuperclass
    table: hezten_parents
    id: 
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        surname:
            type: string
        email:
            type: string 
            nullable: true 
            unique: true
    OneToMany:
        phones:
            targetEntity: "ParentPhone"
            mappedBy: parent
            cascade: ["persist","remove"]