Hezten\CoreBundle\Entity\State:
    type: mappedSuperclass
    table: hezten_state
    id: 
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 20